<a href="https://colab.research.google.com/github/ramizMahmmud/pytorch/blob/main/1_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch

In [2]:
scalar = torch.tensor(7)

In [3]:
print(scalar.ndim)
print(scalar.shape)

0
torch.Size([])


In [4]:
vector = torch.tensor([5, 6, 7])

In [5]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([3])


In [6]:
MATRIX = torch.tensor([[1,2,3],
                       [4,5,6],
                       [12, 15, 18],
                       [20, 22 ,25]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [12, 15, 18],
        [20, 22, 25]])
2
torch.Size([4, 3])


In [7]:
print(MATRIX[0])

tensor([1, 2, 3])


In [8]:
# print 15 from MATRIX
# row = 2 (satrt from 0)
# column = 1 (strat from 0)

print(MATRIX[2][1])

tensor(15)


In [9]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [10,12,14],
                         [15,16,19]]
                       ])

In [10]:
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [10, 12, 14],
         [15, 16, 19]]])
3
torch.Size([1, 4, 3])


In [11]:
# access 12
print(TENSOR[0][2][1])

tensor(12)


In [12]:
TENSOR_1 = torch.tensor([[[1,2],[3,4]],
                         [[5,6],[7,8]],
                         [[20,22],[23,25]]])

In [13]:
print(TENSOR_1)
print(TENSOR_1.ndim)
print(TENSOR_1.shape)


tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[20, 22],
         [23, 25]]])
3
torch.Size([3, 2, 2])


# torch.Size([3,2,2])
[mother blcok, child blcok, entries]


In [14]:
# access 23
# mother block = 2 (index start from 0)
# child block = 1
# entry = 0

print(TENSOR_1[2][1][0])

tensor(23)


In [15]:
random_tensor = torch.rand(size=(3, 4))
print(random_tensor)
print(random_tensor.shape)

tensor([[0.1574, 0.3553, 0.4428, 0.5793],
        [0.6352, 0.1177, 0.4932, 0.1415],
        [0.2743, 0.3124, 0.1471, 0.7575]])
torch.Size([3, 4])


In [16]:
#Getting informatio

print(random_tensor.shape)
print(random_tensor.dtype)
print(random_tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [17]:
# Basic Multiplication
x = torch.tensor([1,2,3,4])

print(x+100)
print(x-20)
print(x*10)
print(x/2)

tensor([101, 102, 103, 104])
tensor([-19, -18, -17, -16])
tensor([10, 20, 30, 40])
tensor([0.5000, 1.0000, 1.5000, 2.0000])


In [22]:
# Multiplication (Dot product)
x = torch.tensor([1, 2, 3])
y = torch.tensor([5, 6 ,7])
print(x.shape)
print(y.shape)

torch.Size([3])
torch.Size([3])


In [23]:
print(x*y)

tensor([ 5, 12, 21])


In [25]:
x = torch.tensor([[1,2,3], [5,6,7]])
y = torch.tensor([[2,3, 5], [2, 3, 2]])

print(f"Order of x: {x.shape}.\nOrder of y: {y.shape}")

Order of x: torch.Size([2, 3]).
Order of y: torch.Size([2, 3])


In [28]:
# for matrix multiplication order matrices must be (m x n) and (n x p)
# order of result of multiplication (m x p)
z = torch.matmul(x, y.T) # .T is used for transpose
print(z, z.shape)

tensor([[23, 14],
        [63, 42]]) torch.Size([2, 2])


Finding min, max, mean

In [30]:
x = torch.arange(start=0, end= 100, step= 3)
print(x)

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
        54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])


In [32]:
print(f"Minimum: {x.min()}")
print(f"Max: {x.max()}")
print(f"Sum: {x.sum()}")

Minimum: 0
Max: 99
Sum: 1683


In [34]:
# Mean/ average works only on float data type

Mean = x.type(torch.float32).mean()
print(Mean)

tensor(49.5000)
