<a href="https://colab.research.google.com/github/ramizMahmmud/pytorch/blob/main/1_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch

In [2]:
scalar = torch.tensor(7)

In [3]:
print(scalar.ndim)
print(scalar.shape)

0
torch.Size([])


In [5]:
vector = torch.tensor([5, 6, 7])

In [6]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([3])


In [9]:
MATRIX = torch.tensor([[1,2,3],
                       [4,5,6],
                       [12, 15, 18],
                       [20, 22 ,25]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [12, 15, 18],
        [20, 22, 25]])
2
torch.Size([4, 3])


In [10]:
print(MATRIX[0])

tensor([1, 2, 3])


In [11]:
# print 15 from MATRIX
# row = 2 (satrt from 0)
# column = 1 (strat from 0)

print(MATRIX[2][1])

tensor(15)


In [13]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [10,12,14],
                         [15,16,19]]
                       ])

In [22]:
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [10, 12, 14],
         [15, 16, 19]]])
3
torch.Size([1, 4, 3])


In [16]:
# access 12
print(TENSOR[0][2][1])

tensor(12)


In [23]:
TENSOR_1 = torch.tensor([[[1,2],[3,4]],
                         [[5,6],[7,8]],
                         [[20,22],[23,25]]])

In [24]:
print(TENSOR_1)
print(TENSOR_1.ndim)
print(TENSOR_1.shape)


tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[20, 22],
         [23, 25]]])
3
torch.Size([3, 2, 2])


# torch.Size([3,2,2])
[mother blcok, child blcok, entries]


In [25]:
# access 23
# mother block = 2 (index start from 0)
# child block = 1
# entry = 0

print(TENSOR_1[2][1][0])

tensor(23)
