<a href="https://colab.research.google.com/github/ramizMahmmud/pytorch/blob/main/1_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch

In [2]:
scalar = torch.tensor(7)

In [3]:
print(scalar.ndim)
print(scalar.shape)

0
torch.Size([])


In [4]:
vector = torch.tensor([5, 6, 7])

In [5]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([3])


In [6]:
MATRIX = torch.tensor([[1,2,3],
                       [4,5,6],
                       [12, 15, 18],
                       [20, 22 ,25]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [12, 15, 18],
        [20, 22, 25]])
2
torch.Size([4, 3])


In [7]:
print(MATRIX[0])

tensor([1, 2, 3])


In [8]:
# print 15 from MATRIX
# row = 2 (satrt from 0)
# column = 1 (strat from 0)

print(MATRIX[2][1])

tensor(15)


In [9]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [10,12,14],
                         [15,16,19]]
                       ])

In [10]:
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [10, 12, 14],
         [15, 16, 19]]])
3
torch.Size([1, 4, 3])


In [11]:
# access 12
print(TENSOR[0][2][1])

tensor(12)


In [12]:
TENSOR_1 = torch.tensor([[[1,2],[3,4]],
                         [[5,6],[7,8]],
                         [[20,22],[23,25]]])

In [13]:
print(TENSOR_1)
print(TENSOR_1.ndim)
print(TENSOR_1.shape)


tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[20, 22],
         [23, 25]]])
3
torch.Size([3, 2, 2])


# torch.Size([3,2,2])
[mother blcok, child blcok, entries]


In [14]:
# access 23
# mother block = 2 (index start from 0)
# child block = 1
# entry = 0

print(TENSOR_1[2][1][0])

tensor(23)


In [15]:
random_tensor = torch.rand(size=(3, 4))
print(random_tensor)
print(random_tensor.shape)

tensor([[0.3964, 0.2737, 0.1617, 0.5395],
        [0.8717, 0.1626, 0.2664, 0.9654],
        [0.4582, 0.2843, 0.6749, 0.6233]])
torch.Size([3, 4])


In [16]:
#Getting informatio

print(random_tensor.shape)
print(random_tensor.dtype)
print(random_tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [17]:
# Basic Multiplication
x = torch.tensor([1,2,3,4])

print(x+100)
print(x-20)
print(x*10)
print(x/2)

tensor([101, 102, 103, 104])
tensor([-19, -18, -17, -16])
tensor([10, 20, 30, 40])
tensor([0.5000, 1.0000, 1.5000, 2.0000])


In [18]:
# Multiplication (Dot product)
x = torch.tensor([1, 2, 3])
y = torch.tensor([5, 6 ,7])
print(x.shape)
print(y.shape)

torch.Size([3])
torch.Size([3])


In [19]:
print(x*y)

tensor([ 5, 12, 21])


In [20]:
x = torch.tensor([[1,2,3], [5,6,7]])
y = torch.tensor([[2,3, 5], [2, 3, 2]])

print(f"Order of x: {x.shape}.\nOrder of y: {y.shape}")

Order of x: torch.Size([2, 3]).
Order of y: torch.Size([2, 3])


In [21]:
# for matrix multiplication order matrices must be (m x n) and (n x p)
# order of result of multiplication (m x p)
z = torch.matmul(x, y.T) # .T is used for transpose
print(z, z.shape)

tensor([[23, 14],
        [63, 42]]) torch.Size([2, 2])


Finding min, max, mean

In [22]:
x = torch.arange(start=0, end= 100, step= 3)
print(x)

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
        54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])


In [23]:
print(f"Minimum: {x.min()}")
print(f"Max: {x.max()}")
print(f"Sum: {x.sum()}")

Minimum: 0
Max: 99
Sum: 1683


In [24]:
# Mean/ average works only on float data type

Mean = x.type(torch.float32).mean()
print(Mean)

tensor(49.5000)


In [27]:
# position of max and min data
print(f"Index of max value: {x.argmax()}")
print(f"Index of min value: {x.argmin()}")

Index of max value: 33
Index of min value: 0


In [28]:
print(x.dtype)

torch.int64


In [31]:
x = x.type(torch.int32)
print(x.dtype)

torch.int32


In [48]:
# Reshaping, stacking, squeezing, unsqueezing
x = torch.arange(1,10,1)
x_reshaped = x.reshape(3,3)
print(x_reshaped)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [49]:
x_view = x.view(3,3)
x_view

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [50]:
print(x.ndim)
print(x.shape)

1
torch.Size([9])


In [53]:
# after changing view changes main tensor, reshape does not
x_view[0][0] =21
x_reshaped[1][1] = 99999
print(x)
print(x_reshaped)
print(x_view)

tensor([   21,     2,     3,     4, 99999,     6,     7,     8,     9])
tensor([[   21,     2,     3],
        [    4, 99999,     6],
        [    7,     8,     9]])
tensor([[   21,     2,     3],
        [    4, 99999,     6],
        [    7,     8,     9]])


In [55]:
x = torch.tensor([[1, 2, 3]])
x_squeezed = x.squeeze()
print(x_squeezed)
print(x_squeezed.shape)

tensor([1, 2, 3])
torch.Size([3])


In [57]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(x_unsqueezed)
print(x_unsqueezed.shape)

tensor([[1, 2, 3]])
torch.Size([1, 3])


In [61]:
x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[11, 12,],[15,18]])
z = torch.tensor([[22, 25, 23]])
w = torch.tensor([[51,52,53],[33,35,36]])

x_stacked_w = torch.stack([x,w], dim=0)
print(x_stacked_w)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[51, 52, 53],
         [33, 35, 36]]])


In [63]:
# selecting specific data
x = torch.arange(1,10).reshape(3,3)
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [67]:
# grab first row
print(x[0])
print(x[0].ndim)

print(x[:,0])
print(x[:,0].ndim)

tensor([1, 2, 3])
1
tensor([1, 4, 7])
1


In [69]:
# Pytorch to numpy and vice versa
import numpy as np

In [70]:
array = np.arange(1, 10)
# convert this array to tensor
tensor = torch.from_numpy(array)

print(f"Numpy Array: {array}")
print(f"Pytorch Tensor: {tensor}")


Numpy Array: [1 2 3 4 5 6 7 8 9]
Pytorch Tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [72]:
tensor += 10
numpy_arr = tensor.numpy()
print(tensor)
print(numpy_arr)

tensor([21, 22, 23, 24, 25, 26, 27, 28, 29])
[21 22 23 24 25 26 27 28 29]


In [73]:
# Reproducibilty
rand_A = torch.rand(3,3)
rand_B = torch.rand(3,3)
print(rand_A)
print(rand_B)

tensor([[0.0345, 0.5715, 0.8532],
        [0.1392, 0.5772, 0.4411],
        [0.2318, 0.0441, 0.4152]])
tensor([[0.6987, 0.3132, 0.4875],
        [0.1103, 0.2475, 0.0923],
        [0.7522, 0.8262, 0.3163]])


In [77]:
import random

RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
rand_C = torch.rand(3,3)

torch.manual_seed(seed = RANDOM_SEED)
rand_D = torch.rand(3,3)

torch.manual_seed(seed= 7)
rand_E = torch.rand(3,3)
torch.manual_seed(seed = 7)
rand_F = torch.rand(3,3)
print(rand_C)
print(rand_D)
print(rand_E)
print(rand_F)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.5349, 0.1988, 0.6592],
        [0.6569, 0.2328, 0.4251],
        [0.2071, 0.6297, 0.3653]])
tensor([[0.5349, 0.1988, 0.6592],
        [0.6569, 0.2328, 0.4251],
        [0.2071, 0.6297, 0.3653]])
